config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "homes#index"
  direct :homepage do "#{root_url}" end

  resources :homes, :posts
  resources :posts, :comments do
    :comments
  end

  resources :posts do
    member do
      get :post_comments
      post :like
    end
  end

  get :search, to: "homes#search"
  resources :homes do
    member do
      get :user_profile
      post :report
    end
  end
  resources :friendships do
    member do
      post :accept_request
      post :unfriend
      post :cancel_request
      patch :accept_or_reject_request
    end
    collection do
      get :requests_received
      get :requests_sent
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @users = User.all.order(:name).page(params[:page])
    @posts = Post.paginate(page: params[:page]).order("created_at DESC")
    respond_to do |format|
      format.csv { send_data @users.to_csv , filename: "users-#{Date.today}.csv" }
      format.html
      format.js
    end
  end

  def user_profile
    @user = User.find(params[:id])
    friendship = current_user.friend_with? @user
    @is_friend = "not_requested" and return unless friendship.present?

    if friendship.status
      @is_friend = true
    else
      @is_friend = false
    end
  end

  def report
    @report = current_user.reports.new(report_params)
    respond_to do |format|
      if @report.save
        @message = 'success'
      else
        @message = 'invalid'
      end
      format.js
    end
  end

  def search
    id = []
    parent_id = []
    @user_result = User.search(params[:q], load: false, fields: [:name], match: :word_start, misspellings: {edit_distance: 2})
    post_result = Post.search(params[:q], load: false, fields: [:text], misspellings: {edit_distance: 2}, aggs: [:user_id])
    comment_result = Comment.search(params[:q], load: false, fields: [:body], misspellings: {edit_distance: 2}, aggs: [:user_id, :post_id])
    if post_result.present?
      post_result.each do |r|
        id << r.id
      end
      @posts = Post.where(id: id).paginate(page: params[:page]).order("created_at ASC")
    end
    if comment_result.present?
      comment_result.each do |c|
        parent_id << c.commentable_id
      end
      @comments = Post.where(id: parent_id)
    end
  end

  def report_params
    params.require(:report).permit(:user_id, :reportable_type, :reportable_id)
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/_get_comments.html.erb
<div class="container">
	<div class="row ">
		<% if !@comments.present? %>
			<h3>No comments Exists</h3>
		<% else @comments %>
			<%= render partial: "comments/comment", collection: @comments%>
		<% end %>
	</div>
</div>

app/views/home/user_profile.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="card background padding posts box my-2 all-comments-show-hide">
      <div class="card-header">
        <div class="row">
          <div class="col-md-10">
            <div class="row">
              <h6><%= @user.name %></h6>
            </div>
            <div class="row">
              <h6><%= @user.created_at.strftime("%d-%m-%Y")%>, <%=@user.created_at.strftime("%I:%M %p")%></h6>
            </div>
          </div>
          <div class="col-md-2">
            <div class="dropdown">
              <a class="test" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></a>
              <ul class="dropdown-menu box">
                <li><%= button_to 'Report', edit_post_path(@user), { method: :get, class: 'dropdown-item', disabled: true } %></li>
                <% if current_user && current_user == @user %>
                <li><%= link_to 'Edit', edit_post_path(@user), { method: :get, class: 'dropdown-item'} %></li>
                <li><%= link_to 'Delete', post_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "delete_post dropdown-item" %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body text-center">
        <div class="row">Email: <%= @user.email%></div>
      </div>
      <div class="card-footer text-center">
        <div class="row">
          <div class="col-md-4 border-right ">
            <% if @user.id == current_user.id %>
            <p> ... </p>
            <% end %>
            <% if @user.id != current_user.id && @is_friend == "not_requested" %>
              <%= button_to "Send Request", friendships_path(friend_id: @user.id), method: :post, class: "btn font font-12", remote: true%>
            <% elsif @user.id != current_user.id && @is_friend == false %>
              <p class= " font font-12"> Already Requested </p>
            <% elsif @user.id != current_user.id && @is_friend == true %>
              <p class= " font font-12"> Already Friends </p>
            <% end %>
          </div>
          <div class="col-md-4 border-right ">
            <button class="btn font font-12 show-comment-btn" , disabled= "true" id=<%= @user.id%> type="button" >Message</button>
          </div>
          <div class="col-md-4 ">
            <%= button_to "Posts", posts_path(@user.id), method: :get, class: "   btn font font-12 ", params: {id: @user.id} %>
          </div>
        </div>
			</div>
    </div>
  </div>
</div>