config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "homes#index"
  direct :homepage do "#{root_url}" end

  resources :homes, :posts
  resources :posts, :comments do
    :comments
  end

  resources :posts do
    member do
      get :post_comments
      post :like
    end
  end

  get :search, to: "homes#search"
  resources :homes do
    member do
      get :user_profile
      post :report
    end
  end
  resources :friendships do
    member do
      post :accept_request
      post :unfriend
      post :cancel_request
      patch :accept_or_reject_request
    end
    collection do
      get :requests_received
      get :requests_sent
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  searchkick
  belongs_to :user
  belongs_to :friend, class_name: "User"
  belongs_to :friendships_requests_sent, foreign_key: "friend_id", class_name: "User"
  validates :friend_id, uniqueness: { scope: :user_id, message: "Already Sent" }

  after_update :add_friend , unless: :already_friends?
  after_destroy :destroy_friend, if: :already_friends?

  def self.existing_friends(user_id, friend_id)
    find_by_user_id_and_friend_id(user_id, friend_id)
  end

  def add_friend
    if saved_change_to_attribute?('status')
      if status == true
        self.class.create(inverse_options)
      end
    end
  end

  def destroy_friend
    inverses.destroy_all
  end

  def already_friends?
    self.class.exists?(inverse_options)
  end

  def inverses
    self.class.where(inverse_options)
  end

  def inverse_options
    { friend_id: user_id, user_id: friend_id, status: true }
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :destroy_friendship, only: [:cancel_request, :unfriend]

  def destroy_friendship
    current_user.friendships.where(friend_id: params[:id]).first&.destroy!
  end

  def new
    @users = User.all_except(current_user).order(:name).page(params[:page])
  end

  def create
    @friendship = current_user.friendships.new(friend_id: params[:friend_id])
    if @friendship.save
      flash[:success] = "Request sent successfully"
    else
      flash[:error] = "Already Friends"
    end
    redirect_to new_friendship_path
  end

  def accept_request
    @friendship = Friendship.existing_friends(params[:id], current_user.id)
  end

  def accept_or_reject_request
    @friendship = Friendship.find(params[:id])
    flash[:success] = params[:friendship][:status]
    if params[:friendship][:status] == 'true' && @friendship.update(friend_params)
      flash[:success] = "Request Accepted"
    elsif params[:friendship][:status] == 'false' && @friendship.update(friend_params)
      flash[:success] = "Request Rejected"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to friendships_path
  end

  def requests_received
    @friends_req = current_user.friendships_requests_received.order(created_at: :desc).page(params[:page])
  end

  def requests_sent
    @friendships_requests_sent = current_user.friendships_requests_sent.order(:name).page(params[:page])
  end

  def index
    @friends = current_user.friends.order(:name).page(params[:page])
  end

  def cancel_request
    redirect_to requests_sent_friendships_path
  end

  def unfriend
    redirect_to friendships_path
  end

  private
  def friend_params
    params.require(:friendship).permit(:user_id, :friend_id, :status)
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friend.html.erb
<div class="row my-3">
  <div class=" col-md-9">
    <div class="row">
      <div class=" col-md-3"><%= friend.name%></div>
      <div class=" col-md-7"><%= friend.email%></div>
      <div class=" col-md-2"><%= friend.id%></div>
    </div>
  </div>
  <div class=" col-md-3">
    <%= button_to 'Unfriend', unfriend_friendship_path(friend), method: :post, class: "btn float-left  btn-background blue font font-12", data: { confirm: 'Are you sure?' }  if is_friend%>
    <%= button_to 'Cancel Request', cancel_request_friendship_path(friend), method: :post, class: "btn float-left  btn-background blue font font-12", data: { confirm: 'Are you sure?' }  unless is_friend %>
  </div>
</div>

app/views/friendships/_friend_request_recieved.html.erb
<div class="row my-3">
  <div class=" col-md-8">
    <div class="row">
      <div class=" col-md-3"><%= friend_request_recieved.user.name%></div>
      <div class=" col-md-7"><%= friend_request_recieved.user.email%></div>
      <div class=" col-md-2"><%= friend_request_recieved.user.id%></div>
    </div>
  </div>
  <div class=" col-md-4">
    <%= button_to 'Accept or Reject Request', accept_request_friendship_path(friend_request_recieved.user) , method: :post, class: " btn font font-12 btn-background blue"%>
  </div>
</div>

app/views/friendships/accept_request.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background forgot_password">
      <div class="card-header">
				<h3>Friend Request</h3>
			</div>
      <div class="card-body">
        <%= form_for(@friendship, url: { action: "accept_or_reject_request", id: @friendship }) do |form| %>

          <div class=" form-group">
            <%= form.radio_button :status, 'true'%>
            <%= form.label :status, "Accept" %><br>
          </div>
          <div class=" form-group">
            <%= form.radio_button :status, 'false', checked: true %>
            <%= form.label :status, "Reject" %><br>
          </div>
          <div class="form-group">
            <%= form.submit "Update", class: "btn float-right btn-default font font-12 btn-background blue"%>
          </div>

        <% end %>
      </div>
      <div class="card-footer">
				<%= button_to "Back", requests_received_friendships_path(@friendship), { method: :get, class: "btn float-left font font-12 btn-background blue" } %>
			</div>
    </div>
  </div>
</div>

app/views/friendships/edit.html.erb
<%= form_for(@friend) do |form| %>
  <p>
    <%= form.label :status %><br>
    <%= form.radio_button :status, 'true'%>
    <%= form.label :status, "Accept" %><br>
    <%= form.radio_button :status, 'false', :checked => true %>
    <%= form.label :status, "Reject" %><br>
    
    <%= form.submit %>
  </p>
<% end %>
<%= link_to "Back", friendships_path %> 



app/views/friendships/friend_requests.html.erb
<% if @friends_req.empty?%>
  <h2>No Friend Requests</h2>
<% else @friends_req %>
  <h1> Friend Requests </h1>
  <%= render partial: "friend", collection: @friends_req, :locals => {:greeting => '1'}%>
<%end%>

app/views/friendships/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background friends">
      <div class="card-header">
				<% if @friends.present? %>
        <h3>Friends</h3>
          <%= will_paginate @friends %>
          <div class="row">
            <div class=" col-md-9">
              <div class="row">
                <div class=" col-sm-3 "> Name</div>
                <div class=" col-sm-6 "> Email</div>
                <div class=" col-sm-2 margin"> id</div>
              </div>
            </div>
          </div>
        <% else %>
          <h3>No Friends Exists</h3>
        <% end %>
      </div>
      <div class="card-body">
        <% if @friends.present? %>
          <%= render partial: "friend", collection: @friends, locals: { is_friend: true }%>
        <% end %>
			</div>
      <div class="card-footer">
        <%= will_paginate @friends %>
      </div>
    </div>
  </div>
</div>

app/views/friendships/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background friends">
      <div class="card-header">
				<h3>You can send a Friend Request</h3>
        <%= will_paginate @users %>
        <div class="row form-group">
          <div class=" col-md-9">
            <div class="row">
              <div class=" col-sm-4 "> Name</div>
              <div class=" col-sm-7 "> Email</div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <% @users.each do |user| %>
            <div class=" col-md-9">
              <div class="row">
                <div class=" col-md-4"><%= user.name%></div>
                <div class=" col-md-8"><%= user.email%></div>
              </div>
            </div>
            <div class=" col-md-3 form-group">
              <%= button_to 'Add as Friend' , friendships_path(friend_id: user.id), method: :post, class: "font font-12 btn float-left btn-background blue" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer">
				<%= will_paginate @users %>
			</div>
    </div>
  </div>
</div>

app/views/friendships/requests_received.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background friends">
      <div class="card-header">
        <% if @friends_req.present? %>
        <h3>Friend Requests</h3>
          <%= will_paginate @friends_req %>
          <div class="row">
            <div class=" col-md-9">
              <div class="row">
                <div class=" col-sm-3 "> Name</div>
                <div class=" col-sm-6 "> Email</div>
                <div class=" col-sm-2 "> id</div>
              </div>
            </div>
          </div>
        <% else %>
          <h3>No Friend Requests</h3>
        <% end %>
      </div>
      <div class="card-body">
        <% if @friends_req.present? %>
          <%= render partial: "friend_request_recieved", collection: @friends_req%>
        <% end %>
      </div>
      <div class="card-footer">
        <%= will_paginate @friends_req %>
      </div>
    </div>
  </div>
</div>



app/views/friendships/requests_sent.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background friends">
      <div class="card-header">
				<% if @friendships_requests_sent.present? %>
          <h3>Friend Request Sent</h3>
          <%= will_paginate @friendships_requests_sent %>
          <div class="row">
            <div class=" col-md-9">
              <div class="row">
                <div class=" col-sm-3 "> Name</div>
                <div class=" col-sm-6 "> Email</div>
                <div class=" col-sm-2 margin"> id</div>
              </div>
            </div>
          </div>
        <% else %>
          <h3>No Request Sent</h3>
        <% end %>
      </div>
      <div class="card-body">
        <% if @friendships_requests_sent.present? %>
          <%= render partial: "friend", collection: @friendships_requests_sent, locals: { is_friend: false }%>
        <% end %>
      </div>
      <div class="card-footer">
        <%= will_paginate @friendships_requests_sent %>
      </div>
    </div>
  </div>
</div>