config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "homes#index"
  direct :homepage do "#{root_url}" end

  resources :homes, :posts
  resources :posts, :comments do
    :comments
  end

  resources :posts do
    member do
      get :post_comments
      post :like
    end
  end

  get :search, to: "homes#search"
  resources :homes do
    member do
      get :user_profile
      post :report
    end
  end
  resources :friendships do
    member do
      post :accept_request
      post :unfriend
      post :cancel_request
      patch :accept_or_reject_request
    end
    collection do
      get :requests_received
      get :requests_sent
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  searchkick suggest: [:text]
  self.per_page = 10
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_post_presence, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

	def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        @message = 'success'
				format.js
				format.html { redirect_to posts_path, notice: 'Post was successfully created.'}
      else
        @message = 'invalid'
				format.html { render 'new', error: 'Something went wrong.' }
			end
		end
	end

  def index
    @posts = Post.where(user_id: params[:id]).order(:created_at).page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
      if @post.update!(post_params)
        flash[:success] = "Post successfully updated"
        redirect_to root_url
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def post_comments
    @post = Post.find_by_id(params[:id])
    if @post.present?
      @comments = @post.comments
      render partial: "post_comments"
		else
			flash[:error] = "Post with 'Id = #{params[:id]} not available"
			redirect_to root_url
    end
  end

  def like
    @like = Like.where(like_params.merge({ user_id: current_user.id })).first
    respond_to do |format|
      if !@like.present?
        @like = current_user.likes.new(like_params)
        if (@like.new_record? && @like.save) || (@like.persisted? && @like.save)
          @message = 'success'
        else
          @message = 'invalid'
        end
      else
        if @like.destroy
          @message = 'success'
        else
          @message = 'invalid'
        end
      end
      format.js
    end
  end

  def destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to root_url, notice: 'Post was successfully deleted.' }

      else
        format.html { redirect_to root_url, notice: 'Something went wrong.' }
      end
      format.json { head :no_content }
      format.js   { render layout: false }
   end
  end

  private
  def check_post_presence
    post = Post.find_by_id(params[:id])
    if post.present?
			@post = post
		else
			flash[:error] = "Post with 'Id = #{params[:id]} is not available"
			redirect_to root_url
    end
  end

  def like_params
    params.require(:like).permit(:user_id, :likeable_type, :likeable_id)
  end

  def post_params
    params.require(:post).permit(:id, :user_id, :text, comments_attributes: [:user_id, :body, :commentable_type, :commentable_id, :_destroy])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path, remote: true, html: { id: 'post-form'} do |f| %>

  <div class="input-group form-group">
    <%= f.text_area :text, autofocus: true, id: 'posts__response-text', autocomplete: "text",rows: "4", class: "form-control", placeholder: "Enter text here.." %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn float-right btn-default btn-background blue font font-12" %>
  </div>

<% end %>

app/views/posts/_form_newcomment.html.erb
<%= form_for :comment, url: comments_path, remote: true, html: { class: "comment-form" ,id: 'comment-form'} do |f| %>
  <div class="row">
    <div class="col-md-9">
      <%= f.text_area :body, class:"form-control", id: "comments__response-text#{commentable.id}", rows: "1", placeholder: "Add comment here..."%>
      <%= f.hidden_field :commentable_id, value: "#{commentable.id}" %>
      <%= f.hidden_field :commentable_type, value: "#{commentable_type}" %>
    </div>
    <div class="col-md-3 ">
      <%= f.submit "Submit", class: "btn btn-background blue font font-12 " %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background padding posts box my-2 all-comments-show-hide">
      <div class="card-header">
        <div class="row">
          <% liked = Like.find_by( likeable_type: "Post", likeable_id: post.id, user: current_user ) %>
          <div class="col-md-10">
            <div class="row">
              <h6><%= link_to post.user.name, user_profile_home_path(post.user.id), { method: :get} %></h6>
            </div>
            <div class="row">
              <h6><%=post.created_at.strftime("%d-%m-%Y")%>, <%=post.created_at.strftime("%I:%M %p")%></h6>
            </div>
          </div>
          <div class="col-md-2">
            <div class="dropdown">
              <a class="test" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></a>
              <ul class="dropdown-menu box">
                <% if reported = Report.find_by( reportable_type: "Post", reportable_id: post.id, user: current_user ) != nil %>
                  <li><%= button_to 'Report', report_home_path(post), method: :post, class: 'dropdown-item like color-blue color-toggle a', id:"report-post-#{post.id}", remote: true, params: { report: {reportable_type: "Post", reportable_id: post.id } } %></li>
                <% else %>
                  <li><%= button_to 'Report', report_home_path(post), method: :post, class: 'dropdown-item like', id:"report-post-#{post.id}", remote: true, params: { report: {reportable_type: "Post", reportable_id: post.id } } %></li>
                <% end %>
                <% if current_user && current_user == post.user %>
                <li><%= link_to 'Edit', edit_post_path(post), { method: :get, class: 'dropdown-item'} %></li>
                <li><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "delete_post dropdown-item" %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body text-center">
        <div class="row text align"><%= post.text%></div>
      </div>

      <div class="<%= ' like disappear' if post.likes.count == 0 %> tooltip like-tooltip tooltip-position" id="like-count<%=post.id%>"><i class="fa fa-thumbs-up" aria-hidden="true"><div class="inline div-inline" id="like-post-count<%=post.id%>"><%= post.likes.count %></div></i>
          <% post.likes.each do |like| %>
            <span class=" tooltiptext like-tooltip tooltip-position"><%= like.user.name %></span>
          <% end %>
      </div>
      <div class="<%= 'like disappear' if post.likes.count > 0 %>" id="like-text<%=post.id%>"><i class="font font-12" >Be first to like it.</i></div>

      <div class="card-footer text-center">
        <div class="row">
          <div class="col-md-4 border-right ">
            <%= button_to "Like", like_post_path(post.id), class: "#{ 'color-blue color-toggle a' if liked != nil } btn font font-12 like ", id:"like-post-#{post.id}", totalLikes: "#{ post.likes.count }", method: :post, remote: true, params: { like: { likeable_type: "Post", likeable_id: post.id }}%>
          </div>
          <div class="col-md-4 border-right ">
            <button class="btn font font-12 show-comment-btn" id=<%= post.id%> type="button" >Comment</button>
          </div>
          <div class="col-md-4 ">
            <%= button_to "Share", posts_path(post), { method: :get, class: "   btn font font-12 ", disabled: true} %>
          </div>
        </div>
			</div>
      <div class="card-footer comment-area" data-id=<%= post.id %>>
        <div class="form-group shadow-textarea">
          <%= render partial: "posts/form_newcomment", locals: {commentable: post, commentable_type: "Post" } %>
        </div>
        <div class="row" id="comments_section<%= post.id %>" data-post-id="<%= post.id %>"> </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_comments.html.erb
<div class="container">
	<div class="row">
		<% if @comments.present? %>
			<%= render partial: "comments/comment", collection: @comments%>
		<% else %>
			<h6 id= "comments-text<%=@post.id%>"> No comments Exists </h6>
		<% end %>
	</div>
</div>

app/views/posts/_update_form.html.erb
<%= form_for @post do |f| %>
  <div class="input-group form-group">
    <%= f.text_area :text, autofocus: true, autocomplete: "text",rows: "4", class: "form-control", placeholder: "Enter text here.." %>
  </div>
  <div class="form-group">
    <%= f.submit "Update", class: "btn float-right btn-default btn-background blue font font-12" %>
  </div>
<% end %>

app/views/posts/create.js.erb
var message = "<%= escape_javascript(@message) %>";
var responseText = '';
$('#post-form').on("ajax:success", function(e, data, status, xhr){
  if (message == 'success') {
    responseText = '';
  } else if (message == 'invalid') {
    responseText = 'Something is Wrong.';
  } else {
    responseText = 'Please try again later.';
  }
  $('#posts__response-text').val(responseText);
  $('#posts').prepend("<%= j render @post%>");
}).on("ajax:error", function(e, data, status, xhr){
  $('#posts__response-text').val('Please try again later.');
});

app/views/posts/destroy.js.erb
$('.delete_post').bind('ajax:success', function() {
   $(this).closest('.container').fadeOut();
});

app/views/posts/edit.html.erb
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card background forgot_password">
			<div class="card-header">
				<h3>Update Post</h3>
			</div>
			<div class="card-body">
				<%= render 'update_form' %>
			</div>
			<div class="card-footer">
				<%#= button_to "Add image", posts_path(@post), { method: :get, class: "btn float-left font font-12 btn-background blue", disabled: true}%>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card background posts wall">
			<div class="card-header">
			</div>
			<div class="card-body">
				<% if @posts.present? %>
					<h3> Your Posts </h3>
					<%= paginate @posts %>
					<%= render partial: "post", collection: @posts %>
				<% else %>
					<h3> No Posts Exists </h3>
				<% end %>
			</div>
			<div class="card-footer">
				<%= paginate @posts %>
			</div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card background post new">
			<div class="card-header">
				<h3>Create a new post</h3>
			</div>
			<div class="card-body">
				<%= render partial: 'posts/form' %>
			</div>
			<div class="card-footer">
				<%= button_to "Add image", posts_path(@post), { method: :get, class: "btn float-left font font-12 btn-background blue", disabled: true } %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center h-100">
    <div class="card background posts box">
      <div class="row">
        <div class="col-md-10">
          <div class="card-header">
            <h6><%=@post.user.name%></h6>
            <h6><%=@post.created_at.strftime("%d-%m-%Y")%>, <%=@post.created_at.strftime("%I:%M %p")%></h6>
          </div>
        </div>
        <div class="col-md-2">
          <div class="dropdown">
            <a class="test" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></a>
            <ul class="dropdown-menu box">
              <li><%= link_to 'Edit', edit_post_path(@post), { method: :get, class: 'dropdown-item'} %></li>
              <li><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="card-body text-center ">
        <div class="row"><%= @post.text%></div>
        <div class="row">
          <div class="col-md-6">User: <%= @post.user_id%></div>
          <div class="col-md-6">id: <%= @post.id%></div>
        </div>
      </div>
      <div class="card-footer text-right">
        <%= button_to "Like", posts_path(@post), { method: :get, class: "btn float-left font font-12 btn-background blue" } %>
        <%= button_to "Comment", posts_path(@post), { method: :get, class: "  btn font font-12 btn-background blue" } %>
			</div>
    </div>
  </div>
</div>