config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "homes#index"
  direct :homepage do "#{root_url}" end

  resources :homes, :posts
  resources :posts, :comments do
    :comments
  end

  resources :posts do
    member do
      get :post_comments
      post :like
    end
  end

  get :search, to: "homes#search"
  resources :homes do
    member do
      get :user_profile
      post :report
    end
  end
  resources :friendships do
    member do
      post :accept_request
      post :unfriend
      post :cancel_request
      patch :accept_or_reject_request
    end
    collection do
      get :requests_received
      get :requests_sent
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark btn-background blue remember">
			<a class="navbar-brand" >Fakebook</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav remember">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Friends', friendships_path(current_user), :class => "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <% if user_signed_in? %><%=current_user.name %><%end%>
            </a>
            <ul class="dropdown-menu box" aria-labelledby="navbarDropdownMenuLink">
              <% if user_signed_in? %>
                <li><%= link_to "Find Friends", new_friendship_path, :class => "dropdown-item" %></li>
                <li><%= link_to 'Friend Request Sent', requests_sent_friendships_path(current_user), :class => "dropdown-item" %></li>
                <li><%= link_to 'Friend Requests Recieved', requests_received_friendships_path(current_user), :class => "dropdown-item" %></li><hr/>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'dropdown-item'  %></li>
                <li><%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        <form class="form-inline my-lg-0" action="/search">
          <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-blue blue my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>

      <div class="row">
        <% if user_signed_in? %>
          <div class="col-md-2">
            <div class="mt-3 dropdown">
              <a role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= image_tag(image_path("profile.png")) %></a>
                <ul class="dropdown-menu box">
                  <li><%= link_to 'Edit Profile', edit_user_registration_path, { method: :get, :class => 'dropdown-item'} %></li>
                </ul>
            </div>
          </div>
          <div class="col-md-10">
            <span class="navbar-text">
              Dear  <strong><%= current_user.name %></strong><br/> WELCOME to Fakebook
            </span>
          </div>
        <% end %>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key} remember") %>
    <% end %>
    <%= yield %>

  </body>
</html>